import React from 'react';
import LegalLayout from '@/components/LegalLayout';
import { Cookie, Fingerprint, Activity, TerminalSquare } from 'lucide-react';

const Cookies = () => {
  return (
    <LegalLayout title="Cookie Policy" lastUpdated="March 2026">
      
      <p className="text-zinc-400 text-lg font-light leading-relaxed mb-12">
        To maintain state across the AlgoLib engine and ensure seamless authentication, we utilize small local payloads (cookies and localStorage). Here is exactly what we store and why.
      </p>

      <div className="space-y-6">
        
        {/* Type 1: Essential */}
        <div className="flex flex-col md:flex-row gap-6 p-6 rounded-3xl bg-white/[0.02] border border-white/[0.05]">
          <div className="w-12 h-12 rounded-full bg-white/[0.05] flex items-center justify-center shrink-0">
            <Fingerprint className="w-5 h-5 text-white/70" />
          </div>
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h3 className="text-white font-medium text-lg">Strictly Necessary</h3>
              <span className="px-2 py-0.5 rounded border border-red-500/30 text-red-400 text-[10px] uppercase font-mono tracking-widest bg-red-500/10">Required</span>
            </div>
            <p className="text-sm text-zinc-400 leading-relaxed">
              These are cryptographic tokens generated by Firebase Authentication. They are non-negotiable for the platform to function, ensuring that your connection to the developer hub remains secure and authenticated.
            </p>
          </div>
        </div>

        {/* Type 2: Functional */}
        <div className="flex flex-col md:flex-row gap-6 p-6 rounded-3xl bg-white/[0.02] border border-white/[0.05]">
          <div className="w-12 h-12 rounded-full bg-white/[0.05] flex items-center justify-center shrink-0">
            <TerminalSquare className="w-5 h-5 text-white/70" />
          </div>
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h3 className="text-white font-medium text-lg">Functional State</h3>
              <span className="px-2 py-0.5 rounded border border-zinc-500/30 text-zinc-400 text-[10px] uppercase font-mono tracking-widest bg-zinc-500/10">LocalStorage</span>
            </div>
            <p className="text-sm text-zinc-400 leading-relaxed">
              We leverage browser <code>localStorage</code> to cache your interface preferences. For example, this remembers if you have already dismissed the Visualizer Welcome Modal, bypassing redundant prompts on subsequent boots.
            </p>
          </div>
        </div>

        {/* Type 3: Performance */}
        <div className="flex flex-col md:flex-row gap-6 p-6 rounded-3xl bg-white/[0.02] border border-white/[0.05]">
          <div className="w-12 h-12 rounded-full bg-white/[0.05] flex items-center justify-center shrink-0">
            <Activity className="w-5 h-5 text-white/70" />
          </div>
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h3 className="text-white font-medium text-lg">Performance Telemetry</h3>
              <span className="px-2 py-0.5 rounded border border-blue-500/30 text-blue-400 text-[10px] uppercase font-mono tracking-widest bg-blue-500/10">Analytics</span>
            </div>
            <p className="text-sm text-zinc-400 leading-relaxed">
              Anonymous, aggregated tracking payloads used to measure engine frame drops, route interactions, and general traffic, allowing us to continuously optimize the platform's architecture.
            </p>
          </div>
        </div>

      </div>

      <div className="mt-16 p-8 rounded-2xl bg-gradient-to-br from-white/[0.03] to-transparent border border-white/[0.05]">
        <h4 className="text-white font-medium mb-3">Managing Your Preferences</h4>
        <p className="text-sm text-zinc-400 leading-relaxed">
          You maintain full control over your local data via your browser's dev tools or settings. However, executing a strict block on essential cookies will instantly break the authentication handshake, locking you out of the Visualizer and Community networks.
        </p>
      </div>

    </LegalLayout>
  );
};

export default Cookies;