import React, { useEffect, useState } from 'react';
import { supabaseAdmin as supabase } from '../../netlify/functions/utils/supabase';

interface PendingContent {
  id: string;
  title: string;
  slug: string;
  seo_desc: string;
  image_url: string;
  created_at: string;
}

export function AdminContentModeration() {
  const [pendingPosts, setPendingPosts] = useState<PendingContent[]>([]);
  const [loading, setLoading] = useState(true);
  const [processingId, setProcessingId] = useState<string | null>(null);

  useEffect(() => {
    fetchPendingPosts();
  }, []);

  const fetchPendingPosts = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('discover_content')
      .select('id, title, slug, seo_desc, image_url, created_at')
      .eq('status', 'pending')
      .order('created_at', { ascending: false });

    if (!error && data) {
      setPendingPosts(data);
    } else {
      console.error('Error fetching pending posts:', error);
    }
    setLoading(false);
  };

  const handleApprove = async (post: PendingContent) => {
    setProcessingId(post.id);
    try {
      // 1. Update status to 'published' in Supabase
      const { error } = await supabase
        .from('discover_content')
        .update({ status: 'published' })
        .eq('id', post.id);

      if (error) throw error;

      // 2. Trigger Google Indexing API Webhook
      // Note: Ensure this webhook is set up in your Netlify functions to securely call the Google API
      const webhookUrl = '/api/trigger-indexing';
      const fullPostUrl = `https://algolib.com/discover/${post.slug}`;
      
      const indexingResponse = await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: fullPostUrl, type: 'URL_UPDATED' }),
      });

      if (!indexingResponse.ok) {
        console.warn('Post published, but failed to trigger Google Indexing Webhook.');
      }

      // Remove from list
      setPendingPosts((prev) => prev.filter((p) => p.id !== post.id));
      alert('Post Approved & Google Indexing Triggered!');
    } catch (error) {
      console.error('Error approving post:', error);
      alert('Failed to approve post.');
    } finally {
      setProcessingId(null);
    }
  };

  const handleReject = async (id: string) => {
    if (!window.confirm('Are you sure you want to delete this AI-generated post?')) return;
    
    setProcessingId(id);
    try {
      const { error } = await supabase
        .from('discover_content')
        .delete()
        .eq('id', id);

      if (error) throw error;

      setPendingPosts((prev) => prev.filter((p) => p.id !== id));
    } catch (error) {
      console.error('Error rejecting post:', error);
      alert('Failed to reject post.');
    } finally {
      setProcessingId(null);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-12 text-slate-400">
        <svg className="animate-spin h-8 w-8 text-indigo-500 mr-3" viewBox="0 0 24 24" fill="none">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        Loading AI content queue...
      </div>
    );
  }

  return (
    <div className="bg-[#121212] rounded-2xl border border-white/5 p-6 shadow-2xl w-full max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-tight">AI Content Moderation</h2>
          <p className="text-slate-400 mt-1">Review pending posts generated by the Groq Llama 3 Worker.</p>
        </div>
        <div className="bg-indigo-500/10 text-indigo-400 px-3 py-1 rounded-full text-sm font-semibold border border-indigo-500/20">
          {pendingPosts.length} Pending
        </div>
      </div>

      {pendingPosts.length === 0 ? (
        <div className="text-center py-16 bg-black/20 rounded-xl border border-white/5">
          <div className="text-slate-500 mb-2">🎉</div>
          <p className="text-slate-400 font-medium">Queue is empty! All caught up.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {pendingPosts.map((post) => (
            <div 
              key={post.id} 
              className="flex flex-col md:flex-row items-center gap-6 p-5 bg-white/5 hover:bg-white/10 transition-colors border border-white/5 rounded-xl"
            >
              {post.image_url && (
                <img 
                  src={post.image_url} 
                  alt={post.title} 
                  className="w-full md:w-32 h-24 object-cover rounded-lg bg-black/50" 
                />
              )}
              
              <div className="flex-1">
                <h3 className="text-lg font-bold text-white mb-1">{post.title}</h3>
                <p className="text-sm text-slate-400 line-clamp-2">{post.seo_desc}</p>
                <div className="text-xs text-slate-500 mt-2">
                  Slug: <span className="text-slate-400">{post.slug}</span>
                </div>
              </div>

              <div className="flex w-full md:w-auto items-center gap-3">
                <button
                  onClick={() => handleReject(post.id)}
                  disabled={processingId === post.id}
                  className="flex-1 md:flex-none px-4 py-2 bg-red-500/10 hover:bg-red-500/20 text-red-500 font-semibold text-sm rounded-lg border border-red-500/20 transition-colors disabled:opacity-50"
                >
                  Reject (Delete)
                </button>
                <button
                  onClick={() => handleApprove(post)}
                  disabled={processingId === post.id}
                  className="flex-1 md:flex-none px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm rounded-lg shadow-[0_0_20px_rgba(79,70,229,0.3)] transition-all disabled:opacity-50 flex items-center justify-center"
                >
                  {processingId === post.id ? 'Publishing...' : 'Approve & Publish'}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
